//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "kl_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub create_time: Option<DateTime>,
    pub modify_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::kl_user::Entity")]
    KlUser,
}

impl Related<super::kl_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KlUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
